<?php if ((!defined('ABS_PATH'))) exit('ABS_PATH is not loaded. Direct access is not allowed.');
if (!OC_ADMIN) exit('User access is not allowed.'); ?>

<style type="text/css">
	/*textarea {
		width: 100%;
	}
	.ace-custom {
		height: 70vh;
		font-size: 12pt;
		width: 100;
	}*/

    .command { background-color: white; color: #2E2E2E; border: 1px solid black; padding: 8px; }
    .theme-files { min-width: 500px; }

    .d-flex { display: flex; }
    .d-block { display: block; }
</style>

<?php if (is_writable(MetaData::path())) : ?>

	<?php
    $json_name 			= MetaData::$json_name;
    $json_file_path   	= MetaData::path($json_name);
    $json_meta_data 	= MetaData::read_json_file($json_file_path);
    $current_meta_data 	= $json_meta_data;

    $default_meta_data 	= array();

    if (!$json_meta_data) {
    	$default_meta_data = MetaData::default_meta_data();
    	$current_meta_data = $default_meta_data;
    }
    ?>

	<h2 class="render-title"><?php _e('Meta Tags SEO', XTCLASS_THEME_FOLDER); ?></h2>

	<?php if ($json_meta_data) : ?>
	<div class="flashmessage flashmessage-ok d-block">
		<p><h2>JSON:</h2></p>
    	<p><?php _e('The meta tags of this template are generated through the configuration of a JSON file.', XTCLASS_THEME_FOLDER); ?><p>
	</div>
	<?php else : ?>
	<div class="flashmessage flashmessage-info d-block">
		<p><h2>DEFAULT MEDA DATA:</h2></p>
    	<p><?php _e('The meta tags of this template are generated by default metadata. This occurs because there is no JSON file or it is faulty.', XTCLASS_THEME_FOLDER); ?><p>
	</div>
	<?php endif; ?>

	<br>

	<section class="d-flex">
		<div>
			<form action="" method="post">
				<input type="hidden" name="action_specific" value="generate_metadata_json" />
				<button id="button_generate" class="btn btn-mini btn-submit" type="submit"><?php echo osc_esc_html(__('Regenerate JSON file', XTCLASS_THEME_FOLDER)); ?></button>
			</form>
		</div>

		<?php if (file_exists($json_file_path)) : ?>
		<div>
			<form action="" method="post">
		        <input type="hidden" name="action_specific" value="remove_metadata_json" />
		        <input type="hidden" name="target" value="<?php echo $json_name; ?>" />
		        <fieldset>
		            <button id="button_remove" class="btn btn-red btn-mini" type="submit"><?php echo osc_esc_html(__('Remove file', XTCLASS_THEME_FOLDER)); ?></button>
		        </fieldset>
		    </form>
		</div>
		<?php endif; ?>

		<div style="padding-top: 3px;">
			<form action="" method="post" enctype="multipart/form-data" class="nocsrf">
		        <input type="hidden" name="action_specific" value="upload_metadata_json">
		        <!--<input type="hidden" name="target" value="<?php echo $json_name; ?>">-->
		        <fieldset>
		            <div class="form-horizontal">
		                <div class="form-row">
		                    <span><?php _e('JSON file:', XTCLASS_THEME_FOLDER); ?></span>
		                    <input type="file" name="file" id="package">
		                    <button id="button_upload" class="btn btn-submit btn-mini" type="submit"><?php echo osc_esc_html(__('Upload', XTCLASS_THEME_FOLDER)); ?></button>
		                </div>
		            </div>
		        </fieldset>
		    </form>	
		</div>

		<?php if (file_exists($json_file_path)) : ?>
		<div style="padding-top: 3px;">
			<a href="<?php echo osc_admin_render_theme_url('oc-content/themes/'.XTCLASS_THEME_FOLDER.'/admin/settings.php').'&action_specific=download_metadata_json&'.osc_csrf_token_url(); ?>" class="btn btn-submit btn-mini" style="height: 15px; padding-top: 6px;"><?php _e('Download', XTCLASS_THEME_FOLDER); ?></a>
		</div>
		<?php endif; ?>
	</section>

    <?php if (file_exists($json_file_path)) : ?>
    <div class="flashmessage flashmessage-inline flashmessage-warning d-block">
    	<p><?php _e('<strong>Note:</strong> Uploading another file overwrite the current.', XTCLASS_THEME_FOLDER); ?></p>
    </div>
    <?php endif; ?>

    <?php if (!file_exists($json_file_path)) : ?>
	<div class="flashmessage flashmessage-warning flashmessage-inline d-block">
        <p><?php _e('No json file has been uploaded yet.', XTCLASS_THEME_FOLDER); ?></p>
    </div>
	<?php endif; ?>

	<br>

	<h2 class="render-title"><?php _e('Content of the current meta data:', XTCLASS_THEME_FOLDER); ?></h2>
	<div class="d-flex">
		<form id="put-metadata-json" action="" method="post" enctype="multipart/form-data" style="flex: 1; margin-right: 16px;" class="d-flex nocsrf">
			<input type="hidden" name="action_specific" value="put_metadata_json">
			<input type="hidden" name="target" value="<?php echo $json_name; ?>" />
			<textarea name="metadata" data-editor="json" class="ace-custom" data-gutter="1" style="flex: 1;"><?php
			$file_get_contents = null;
			if ($json_meta_data) {
				$file_get_contents = file_get_contents($json_file_path);
			}

			if (!$file_get_contents) {
				echo json_encode($current_meta_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
			} else {
				echo $file_get_contents;
			}
			?></textarea>
		</form>
		
	    <!-- Sidebar -->
	    <aside style="width: 30%; overflow-y: auto; height: 50vh;">
			<div class="well ui-rounded-corners">
				<h2 class="render-title" style="margin: 0;margin-bottom: 10px;text-align: center;"><?php _e('Flags enabled', XTCLASS_THEME_FOLDER); ?></h2>
				<h3 style="color: #616161;"><?php _e('General flags for site and "home":', XTCLASS_THEME_FOLDER); ?></h3>
				<label><b>{BASE_URL}</b><br></label><?php _e('URL Website', XTCLASS_THEME_FOLDER); ?><hr>
				<label><b>{PAGE_TITLE}</b><br></label><?php _e('Website name', XTCLASS_THEME_FOLDER); ?><hr>
				<label><b>{PAGE_DESCRIPTION}</b><br></label><?php _e('Website description', XTCLASS_THEME_FOLDER); ?><hr>
				<label><b>{LOGO}</b><br></label><?php _e('URL of main logo', XTCLASS_THEME_FOLDER); ?><hr>
				<label><b>{META_TAG_FILTER}</b><br></label><?php echo "osc_apply_filter('meta_tag_filter', \$data = '');"; ?><hr>
				<label><b>{META_TITLE_FILTER}</b><br></label><?php echo "osc_apply_filter('meta_title_filter', \$text = '');"; ?><hr>
				<label><b>{META_DESCRIPTION_FILTER}</b><br></label><?php echo "osc_apply_filter('meta_description_filter', \$text = '');"; ?><hr>
				
				<h3 style="color: #616161;">"item":</h3>
				<label><b>{ITEM_IMAGE}</b><br><?php _e('First image of item (If it have)', XTCLASS_THEME_FOLDER); ?></label><hr>
				
				<h3 style="color: #616161;">"item", "item/item_add", "item/edit", "item/send_friend", "item/contact":</h3>
				<label><b>{ITEM_TITLE}</b><br><?php _e('Item title', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{ITEM_CATEGORY}</b><br><?php _e('Category of item', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{ITEM_CITY}</b><br><?php _e('City of item', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{ITEM_URL}</b><br><?php _e('URL of item page', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{ITEM_DESCRIPTION}</b><br><?php _e('140 characters of description category content', XTCLASS_THEME_FOLDER); ?></label><hr>
				
				<h3 style="color: #616161;">"item/item_add":</h3>
				<label><b>{PUBLISH_LISTING_TEXT}</b><br>"<?php _e('Publish a listing', XTCLASS_THEME_FOLDER); ?>"</label><hr>
				
				<h3 style="color: #616161;">"item/item_edit":</h3>
				<label><b>{EDIT_LISTING_TEXT}</b><br>"<?php _e('Edit your listing', XTCLASS_THEME_FOLDER); ?>"</label><hr>
				
				<h3 style="color: #616161;">"item/send_friend":</h3>
				<label><b>{SEND_FRIEND_TEXT}</b><br>"<?php _e('Send to a friend', XTCLASS_THEME_FOLDER); ?>"</label><hr>
				
				<h3 style="color: #616161;">"item/contact":</h3>
				<label><b>{CONTACT_SELLER_TEXT}</b><br>"<?php _e('Contact seller', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"page":</h3>
				<label><b>{STATIC_PAGE_TITLE}</b><br><?php _e('Title of static page', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{STATIC_PAGE_TEXT}</b><br><?php _e('140 characters of static page text', XTCLASS_THEME_FOLDER); ?></label><hr>

				<h3 style="color: #616161;">"error":</h3>
				<label><b>{ERROR_TEXT}</b><br>"<?php _e('Error', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"search":</h3>
				<label><b>{ITEM_CATEGORY}</b><br><?php _e('Category of item (if exists)', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{ITEM_CITY}</b><br><?php _e('City of item', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{TITLE_SEARCH_RESULT}</b><br><?php _e('Title of search results', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{DESCRIPTION_SEARCH_RESULT}</b><br><?php _e('120 charactes of description of search results', XTCLASS_THEME_FOLDER); ?></label><hr>

				<h3 style="color: #616161;">"login":</h3>
				<label><b>{LOGIN_TEXT}</b><br>"<?php _e('Login', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"login/recover":</h3>
				<label><b>{RECOVER_YOUR_PASSWORD_TEXT}</b><br>"<?php _e('Recover your password', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"login/forgot":</h3>
				<label><b>{RECOVER_MY_PASSWORD_TEXT}</b><br>"<?php _e('Recover my password', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"register":</h3>
				<label><b>{CREATE_NEW_ACCOUNT_TEXT}</b><br>"<?php _e('Create a new account', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user":</h3>
				<label><b>{USER_NAME}</b><br><?php _e('Name of user', XTCLASS_THEME_FOLDER); ?></label><hr>
				<label><b>{USER_INFO}</b><br><?php _e('Information of user', XTCLASS_THEME_FOLDER); ?></label><hr>

				<h3 style="color: #616161;">"user/dashboard":</h3>
				<label><b>{DASHBOARD_TEXT}</b><br>"<?php _e('Dashboard', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/items":</h3>
				<label><b>{MANAGE_MY_LISTING_TEXT}</b><br>"<?php _e('Manage my listings', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/alerts":</h3>
				<label><b>{MANAGE_MY_ALERTS_TEXT}</b><br>"<?php _e('Manage my alerts', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/profile":</h3>
				<label><b>{UPDATE_MY_PROFILE_TEXT}</b><br>"<?php _e('Update my profile', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/pub_profile":</h3>
				<label><b>{PUBLIC_PROFILE_TEXT}</b><br>"<?php _e('Public profile', XTCLASS_THEME_FOLDER); ?>"</label><hr>
				<label><b>{USER_NAME}</b><br><?php _e('Name of user', XTCLASS_THEME_FOLDER); ?></label><hr>

				<h3 style="color: #616161;">"user/change_email":</h3>
				<label><b>{CHANGE_MY_EMAIL_TEXT}</b><br>"<?php _e('Change my email', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/change_username":</h3>
				<label><b>{CHANGE_MY_USERNAME_TEXT}</b><br>"<?php _e('Change my username', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/change_password":</h3>
				<label><b>{CHANGE_MY_PASSWORD_TEXT}</b><br>"<?php _e('Change my password', XTCLASS_THEME_FOLDER); ?>"</label><hr>

				<h3 style="color: #616161;">"user/change_password":</h3>
				<label><b>{CUSTOM_PAGE_TITLE}</b><br><?php _e('Title of custom page', XTCLASS_THEME_FOLDER); ?></label><hr>
			</div>
		</aside>
	</div>

	<br>

	<section class="d-flex">
		<div>
			<button form="put-metadata-json" class="btn btn-submit btn-mini" type="submit"><?php echo osc_esc_html(__('Save', XTCLASS_THEME_FOLDER)); ?></button>
		</div>	
		<div style="padding-top: 8px;">
			<?php _e('Online tools:', XTCLASS_THEME_FOLDER); ?> 
			<a href="https://unminify.com/" target="_blank">https://unminify.com/</a>
		</div>
	</section>

	<?php
		// Add help section
		if (file_exists(WebThemes::newInstance()->getCurrentThemePath().'admin/metatags/help.php')) {
			osc_current_web_theme_path('admin/metatags/help.php');
		}

		// Add js at the footer
		osc_add_hook('admin_footer', function() {
			//echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.9/ace.js"></script>'.PHP_EOL;
			//echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.9/ext-language_tools.js"></script>'.PHP_EOL;
			echo '<script src="'.osc_current_web_theme_url('admin/metatags/metatags.js').'"></script>';
		});
	?>

<?php else : ?>

	<div class="flashmessage flashmessage-error d-block">
        <p>
    	<?php
        $msg  = sprintf(__('The folder <strong>%s</strong> is not writable on your server', XTCLASS_THEME_FOLDER), MetaData::path() ) .", ";
        $msg .= __("Osclass can't upload the files from the administration panel.", XTCLASS_THEME_FOLDER) . ' ';
        $msg .= __('Please make the folder writable.', XTCLASS_THEME_FOLDER) . ' ';
        echo $msg;
        ?>
        </p>
        <p><?php _e('To make a directory writable under UNIX execute this command from the shell:', XTCLASS_THEME_FOLDER); ?></p>
        <p class="command">chmod a+w <?php echo MetaData::path(); ?></p>
    </div>

<?php endif; ?>